# Generated by Django 5.0.4 on 2024-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_todotask_end_by_alter_todotask_start_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='note',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
